#!/bin/bash
scriptlist="main.f90 \
additional.f90 \
emcee_module.f90 \
Main_Code.F90 \
mcmc.F90 \
modules.f90 \
OpenAnalysis.f90 \
plot_figure.f90 \
SetFunction_CI.f90 \
SetFunction_CO.f90 \
SetFunctionH2.f90 \
SetFunction_HD.f90 \
SetFunctionHD.f90 \
SZ_effect.f90 \
uv_intensity.f90"

directorylist="1 2 3"

cd /home/ilya/Documents/SSW_NIR/CMB/some\ code/TzInAmplitude/MCMCcodeForLinux
#ls
ind=0
for dir in $directorylist
do
let "ind=ind+1"
pathtodir="/home/ilya/Documents/SSW_NIR/CMB/some code/TzInAmplitude/$dir/"
echo "$pathtodir"OUT/

touch echo.dat
touch echocompile.dat

cp -r "$pathtodir"SZdatas/ ./
cp -r "$pathtodir"priors/ ./

mpifort $scriptlist 2>> echocompile.dat
mpirun -np 4 ./a.out $ind >> echo.dat 

mv OUT/ "$pathtodir"
mv echo.dat "$pathtodir"
mv echocompile.dat "$pathtodir"
mkdir OUT

rm -r ./SZdatas/
rm -r ./priors/

done
