#!/bin/bash
scriptlist="modules.f90 \
emcee_module.f90 \
SetFunction_CI.f90 \
SetFunction_CO.f90 \
SetFunctionH2.f90 \
SetFunction_HD.f90 \
SetFunctionHD.f90 \
SZ_effect.f90 \
uv_intensity.f90 \
mcmc.F90 \
main.f90 \
additional.f90 \
Main_Code.F90 \
OpenAnalysis.f90 \
plot_figure.f90"


mpifort -O2 -s -fallow-argument-mismatch $scriptlist -o Main.out #2> err.dat



